Repository ultralytics/notebooks, pull requests merged in 2025-01, with the labels that each got.

#21 Google colab links fix
  README.md
  notebooks/how-to-count-the-objects-using-ultralytics-yolo.ipynb
  notebooks/how-to-generate-heatmaps-using-ultralytics-yolo.ipynb
  notebooks/how-to-monitor-workouts-using-ultralytics-yolo.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-brain-tumor-detection-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-carparts-segmentation-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-medical-pills-dataset.ipynb
  notebooks/how-to-use-ultralytics-yolo-with-sahi.ipynb
Labels: documentation, enhancement

#22 Update colab notebooks
  notebooks/how-to-count-the-objects-using-ultralytics-yolo.ipynb
  notebooks/how-to-generate-heatmaps-using-ultralytics-yolo.ipynb
  notebooks/how-to-monitor-workouts-using-ultralytics-yolo.ipynb
Labels: detect, pose, segment

#24 Ultralytics Refactor https://ultralytics.com/actions
  notebooks/how-to-generate-heatmaps-using-ultralytics-yolo.ipynb
  notebooks/how-to-monitor-workouts-using-ultralytics-yolo.ipynb
Labels: documentation, enhancement

#23 Update workouts-monitoring notebook
  notebooks/how-to-monitor-workouts-using-ultralytics-yolo.ipynb
Labels: documentation, enhancement, pose

#25 Eliminate non-supported badges
  notebooks/how-to-train-ultralytics-yolo-on-brain-tumor-detection-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-carparts-segmentation-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-medical-pills-dataset.ipynb
  notebooks/how-to-use-ultralytics-yolo-with-sahi.ipynb
Labels: documentation

#27 Update colab notebooks
  README.md
  notebooks/how-to-train-ultralytics-yolo-on-carparts-segmentation-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-package-segmentation-dataset.ipynb
Labels: documentation, segment, track

#29 Update ci.yaml to ci.yml
  notebooks/how-to-count-the-objects-using-ultralytics-yolo.ipynb
  notebooks/how-to-generate-heatmaps-using-ultralytics-yolo.ipynb
  notebooks/how-to-monitor-workouts-using-ultralytics-yolo.ipynb
  notebooks/how-to-track-the-objects-in-zone-using-ultralytics-yolo.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-brain-tumor-detection-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-carparts-segmentation-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-medical-pills-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-package-segmentation-dataset.ipynb
  notebooks/how-to-use-ultralytics-yolo-with-sahi.ipynb
Labels: documentation, devops

#30 Update `ci.yml` badge
  notebooks/how-to-count-the-objects-using-ultralytics-yolo.ipynb
  notebooks/how-to-generate-heatmaps-using-ultralytics-yolo.ipynb
  notebooks/how-to-monitor-workouts-using-ultralytics-yolo.ipynb
  notebooks/how-to-track-the-objects-in-zone-using-ultralytics-yolo.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-brain-tumor-detection-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-carparts-segmentation-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-medical-pills-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-package-segmentation-dataset.ipynb
  notebooks/how-to-use-ultralytics-yolo-with-sahi.ipynb
Labels: documentation, devops

#31 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
  pyproject.toml
Labels: documentation, devops

#32 Add automatic number plate recognition notebook
  README.md
  notebooks/how-to-use-ultralytics-yolo-with-openai-for-number-plate-recognition.ipynb
Labels: documentation, enhancement, detect

#33 Add RKNN export format in notebooks
  notebooks/how-to-count-the-objects-using-ultralytics-yolo.ipynb
  notebooks/how-to-generate-heatmaps-using-ultralytics-yolo.ipynb
  notebooks/how-to-monitor-workouts-using-ultralytics-yolo.ipynb
  notebooks/how-to-track-the-objects-in-zone-using-ultralytics-yolo.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-brain-tumor-detection-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-carparts-segmentation-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-medical-pills-dataset.ipynb
  notebooks/how-to-train-ultralytics-yolo-on-package-segmentation-dataset.ipynb
  notebooks/how-to-use-ultralytics-yolo-with-openai-for-number-plate-recognition.ipynb
  notebooks/how-to-use-ultralytics-yolo-with-sahi.ipynb
Labels: documentation, exports
